client_id = "966c98da8c1bdfd13d71f545ce855716"
name = "Plant Bot Bundle App"
application_url = "https://teens-teddy-survivor-reply.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = false

[access_scopes]
scopes = "read_products,write_products,read_inventory,write_inventory,read_orders"

[auth]
redirect_urls = [
  "https://teens-teddy-survivor-reply.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "orders/cancelled" ]
  uri = "/webhooks/orders/cancelled"

  [[webhooks.subscriptions]]
  topics = [ "products/delete" ]
  uri = "/webhooks/products/delete"

[pos]
embedded = false
